print("Q.36  If X = 1 in the logic equation [X + Z{Y' + (Z' + XY')}]{X' + Z'(X + Y)} = 1, then");
print("(A) Y = Z                    (B) Y = Z'");
print("(C) Z = 1                    (D) Z = 0");
print("\nSolution:");
print("X = 1");
print("Let us substitute that X = 1 in above logic equation:");
print("We know:");
print("1 + A =1");
print();
print("[1 + Z{Y' + (Z' + 1.Y')}]{0 + Z'(1 + Y)} = 1");
print("[1 + Z{Y' + (Z' + Y')}]{0 + Z'.1} = 1");
print("[1 + Z{Y' + Z'}]{Z'} = 1");
print("[1 + ZY']Z' = 1");
print("1.Z' = 1");
print("Z' = 1");
print();
print("We know:");
print("Correct option:(D)   Z' = 1 --> Z = 0");
