print("Q.16 The current through the zener diode in figure is");
print();
print("(A) 33 mA                        (B) 3.3 mA");
print("(C) 2 mA                         (D) 0 mA");
print();
print("Solution:");
Vin = 10.0;            
Vz = 3.3;            
R1 = 2200;       
Rz = 100;              
V_R2 = 3.5;
print("Input Voltage:",Vin);
print("Zener diode voltage:",Vz);
print("Series resistance in ohms:",R1);
print("Zener resistance in ohms:",Rz);
print("Voltage across load resistor:",V_R2);
print();
V_R = Vin - Vz;
print("Voltage across series resistor:",V_R);
I_total = V_R / R1;
print("The total current from the source:",I_total);
V_F = V_R2 - Vz;
print("The voltage drop across Zener resistance:",V_F);
Iz = V_F / Rz
print("Current through zener diode:",Iz);
print();
print("Converting the current into milliamperes");
I_total_mA = I_total * 1000;
Iz_mA = Iz * 1000;
print(f"Total current from source: {I_total_mA:.2f} mA");
print(f"Zener diode current: {Iz_mA:.2f} mA");
print();
print(f"Correct Answer: (C) {Iz_mA:.2f} mA");
